name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest
        pip install -r requirements.txt
        pip install shapely
        pip install geopandas
    - uses: ibnesayeed/setup-ipfs@master
      with:
        run_daemon: true
    - name: Test with pytest
      run: |
        pytest dweather_client/tests
